version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8.8
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps2-{{ checksum "requirements/dev.txt" }}
          paths:
            - 'venv'
      - run:
          command: |
            . venv/bin/activate
            pytest